// Emits src/lib/sqlWasm.ts containing the SQLite WASM binary as base64.
// Passing this to sql.js as `wasmBinary` means the engine is NEVER fetched at
// runtime — which is what lets us keep CSP `connect-src 'none'` (standards.md §4).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const wasm = readFileSync(join(root, "node_modules/@vlcn.io/wa-sqlite/dist/crsqlite.wasm"));
const b64 = wasm.toString("base64");

const out = `// AUTO-GENERATED by scripts/gen-wasm.mjs — do not edit.
// SQLite WASM (${wasm.length} bytes) inlined as base64 so the engine loads
// entirely from memory (no fetch), satisfying CSP connect-src 'none'.
const B64 = "${b64}";

export function sqlWasmBinary(): Uint8Array {
  const bin = atob(B64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}
`;
writeFileSync(join(root, "src/lib/sqlWasm.ts"), out);
console.log(`gen-wasm: wrote src/lib/sqlWasm.ts (${wasm.length} bytes wasm, ${b64.length} b64 chars)`);
